"""add users table

Revision ID: 37141f541c5e
Revises: 0001_add_knowledge_tables
Create Date: 2026-02-24 19:30:58.144592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37141f541c5e'
down_revision: Union[str, Sequence[str], None] = '0001_add_knowledge_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_finances', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_goals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_identity', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_patterns', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_relationships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_updates', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_updates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_updates', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_updates', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_relationships', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_projects', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_patterns', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_identity', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_goals', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_finances', type_='foreignkey')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
